from scrapxd.fetcher import fetch_film
import scrapxd.parser.film as sf

soup = fetch_film("mulholland-drive")
'''film = sf.parse_film(soup)
print(film)'''
print(f"Film ID: {sf.parse_id(soup)}")
print()
print(f"Film slug: {sf.parse_slug(soup)}")
print()
print(f"Title: {sf.parse_title(soup)}")
print()
print(f"Directed by {sf.parse_director(soup)}")
print()
print(f"Released in {sf.parse_year(soup)}")
print()
print(f"Runtime: {sf.parse_runtime(soup)} mins")
print()
print(f"Cast (Actor: Character): {sf.parse_cast(soup)}")
print()
print(f"Crew (Role: Person): {sf.parse_crew(soup)}")
print()
print(f"Studios: {sf.parse_studio(soup)}")
print()
print(f"Genres: {sf.parse_genre(soup)}")
print()
print(f"Themes: {sf.parse_themes(soup)}")
print()
print(f"Nanogenres: {sf.parse_nanogenres(soup)}")
print()
print(f"Country: {sf.parse_country(soup)}")
print()
print(f"Language: {sf.parse_language(soup)}")
print()
print(f"Average Rating: {sf.parse_avg_rating(soup)}")
print()
print(f"Total Logs: {sf.parse_total_logs(soup)}")
print()
print(f"Actors: {sf.parse_actors(soup)}")
print()
print(f"Characters: {sf.parse_characters(soup)}")
