from scrapxd.models.film import Film

film = Film(slug="mulholland-drive")

print(f"Film ID: {film.id}")
print()
print(f"Film slug: {film.slug}")
print()
print(f"Title: {film.title}")
print()
print(f"Directed by {film.director}")
print()
print(f"Released in {film.year}")
print()
print(f"Runtime: {film.runtime} mins")
print()
print(f"Cast (Actor: Character): {film.cast}")
print()
print(f"Crew (Role: Person): {film.crew}")
print()
print(f"Studios: {film.studio}")
print()
print(f"Genres: {film.genre}")
print()
print(f"Themes: {film.themes}")
print()
print(f"Nanogenres: {film.nanogenres}")
print()
print(f"Country: {film.country}")
print()
print(f"Language: {film.language}")
print()
print(f"Average Rating: {film.avg_rating}")
print()
print(f"Total Logs: {film.total_logs}")
print()
print(f"Actors: {film.actors}")
print()
print(f"Characters: {film.characters}")
